add offboarding template
18F/delivery-assurance pull request #126
Opened 2023-04-07 18:54 UTC by MelissaBraxton

2023-04-10 20:44 UTC, geekygirlsarah commented on .github/ISSUE_TEMPLATE/help-request-template.md
> +  take a maximum 2 weeks.
For markdown, the `about:` front matter line can't be on two separate lines. You might need to move "take..." next to "...should"

2023-04-10 20:45 UTC, geekygirlsarah commented on .github/ISSUE_TEMPLATE/offboarding-issue-template.md
> +  cracks!
Same here, these need to be on the same line.

2023-04-11 20:46 UTC, alexbielen requested changes
Two minor changes suggested! Otherwise looks good.

2023-04-11 20:46 UTC, alexbielen commented on .github/ISSUE_TEMPLATE/help-request-template.md
> +about: Request support from the 18F Delivery Assurance Team, each requestion should take a maximum 2 weeks.
Just checking on the word "requestion" -- is that on purpose?

2023-04-11 20:56 UTC, geekygirlsarah commented on .github/ISSUE_TEMPLATE/help-request-template.md
> +about: Request support from the 18F Delivery Assurance Team, each requestion should take a maximum 2 weeks.
requisition?

2023-04-11 21:55 UTC, MelissaBraxton commented on .github/ISSUE_TEMPLATE/offboarding-issue-template.md
> +- [ ] Create a personalized certificate of appreciation to thank them for their contributions!
Made suggested revisions. @alexbielen or @kfoley-18F  - please review and merge (if all looks good), when you have a sec.

2023-04-11 21:58 UTC, kfoley-18F approved these changes
👏 👏 👏

2023-04-11 22:14 UTC, merged